defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


debug: False

device: cpu

display:
  display_flag: False # rich display


wandb:
  enabled: False
  project: generalist_modality_experiment
  tags: null

context_length: 128

model:
  combine_embeddings: False
  model_dim: 768
  latent_seq_len: 32
  encoder_nhead: 4
  decoder_nhead: 4
  encoder_num_layers: 4
  decoder_num_layers: 4
  enable_nested_tensor: True
  use_encoder: True

training:
  batch_size: 4
  learning_rate: 5e-5
  n_epochs: 10
  batch_uniform_dataset_samples: False



predictions:
  initial_generation: True

text_tokenizer:
  name: bert
  vocab_size: 30522 # probably comes from pretrained text_tokenizer
  encode_kwargs:
    return_tensors: pt
    truncation: True
    padding: max_length
    max_length: 400 #  was 512, temporary workaround so text and image have same dim
    return_attention_mask: True

