defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

device: cpu
display: False

context_length: 128

model:
  model_dim: 768
  latent_seq_len: 32
  encoder_nhead: 4
  decoder_nhead: 4
  encoder_num_layers: 4
  decoder_num_layers: 4
  enable_nested_tensor: True

training:
  batch_size: 8
  learning_rate: 5e-5
  n_epochs: 1

tracking:
  project: "2022_neurips_workshop"
# handlers:
#   console:
#     class: rich.logging.RichHandler
# formatter: simple
# stream: ext://sys.stdout
