defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

device: cpu
display: False

model:
  model_dim: 768
training:
  batch_size: 8
  learning_rate: 5e-5
  n_epochs: 1

tracking:
  project: "2022_neurips_workshop"
# handlers:
#   console:
#     class: rich.logging.RichHandler
# formatter: simple
# stream: ext://sys.stdout
