defaults:
  # - /hydra/callbacks/callback
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


debug: False

device: cpu
# display: False

context_length: 128

model:
  model_dim: 768
  latent_seq_len: 32
  encoder_nhead: 4
  decoder_nhead: 4
  encoder_num_layers: 4
  decoder_num_layers: 4
  enable_nested_tensor: True
  use_encoder: True

training:
  batch_size: 2
  learning_rate: 5e-5
  n_epochs: 1

tracking:
  project: "2022_neurips_workshop"

display:
  display_flag: False # rich display
  initial_caption: True

# evalcommand: _helphelp
# eval:
#   command: eval

text_tokenizer:
  return_tensors: pt
  truncation: True
  padding: max_length
  # max_length: 512
  max_length: 400 # temporary workaround so text and image have same dim
  return_attention_mask: True

