defaults:
  - base
  - _self_

device: cuda

log_dir: logs/

# DATA RELATED
coco_dir: /data/graham/datasets/coco/aokvqacoco/datasets/coco # honestly not sure what is this folder versus below
# coco_dir: /data/graham/datasets/coco/coco/images
coco_panoptic: /data/graham/datasets/coco/aokvqacoco/datasets/coco_panoptic

aokvqa_dir: /data/graham/datasets/coco/aokvqacoco
features_dir: /home/graham/code/torchtask/submodules/aokvqa/features
pretrained_models_dir: /home/graham/code/torchtask/pretrained_models

model_save_dir: /data/graham/generalist_runs/models